name: Test

on:
  push:
  pull_request:

jobs:
  emacs-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        emacs_version: [30.1, release-snapshot, snapshot]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Show emacs version
        run: emacs --version
      - name: Run emacs
        run: |
          cd emacs
          ln -s $(pwd) $HOME/.emacs.d
          emacs --debug-init --batch -l init.el
  neovim-tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        nvim-version: [stable, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install Neovim
        shell: bash
        run: |
          wget -q https://github.com/neovim/neovim/releases/download/${{ matrix.nvim-version }}/nvim-linux-x86_64.tar.gz -O /tmp/nvim-linux-x86_64.tar.gz
          sudo tar zxf /tmp/nvim-linux-x86_64.tar.gz -C /tmp/
      - name: Run Neovim
        run: |
          cd nvim
          sudo ln -s $(pwd) ~/.config/nvim
          sudo /tmp/nvim-linux-x86_64/bin/nvim --version
          sudo /tmp/nvim-linux-x86_64/bin/nvim --headless -c "checkhealth" -c "quit" -c "quit"
  vim-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install vim
        shell: bash
        run: sudo apt-get install vim
      - name: Run vim
        run: |
          sudo cp -f .vimrc ~/
          sudo vim --version
